version: "3.8"

services: 
    django: 
        build: .
        container_name: django
        command: make runserver
        volumes: 
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file: 
          - .env
        depends_on: 
          - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        env_file: 
          - .env
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata: