# Generated by Django 3.2.5 on 2021-07-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='release_date',
            new_name='create_date',
        ),
    ]
