# Generated by Django 3.2.5 on 2021-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_release_date_status_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Имя'),
        ),
    ]
