# Generated by Django 3.2.5 on 2021-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='create_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
