name: check

on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'SECRET'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup latest python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run flake8
        run: |
          make lint
      - name: CHEEECK
        run: |
          make check
      # - name: Run tests
      #   run: |
      #     make test
      # - name: Test coverage
      #   uses: paambaati/codeclimate-action@v2.7.5
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      #   with:
      #       coverageCommand: make test-coverage
